name: Keep Sinatra Backend Warm

on:
  schedule:
    - cron: '*/12 * * * *' # every 12 minutes
  workflow_dispatch:       # allows manual triggering too

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl backend
        run: curl -sSf https://backend.sinatra.live || echo "❌ Ping failed"